version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
      - |
        if terraform apply -auto-approve tfplan; then
          echo "Apply successful"
          terraform output -json > tf_output.json
          echo "success" > status.txt
        else
          echo "Apply failed"
          echo "failed" > status.txt
        fi
  post_build:
    commands:
      - echo "Post-build starting"
      - ls -la
      - cat tf_output.json || echo "Output file not found"
      - |
        STATUS=$(cat status.txt)
        if [ "$STATUS" == "success" ]; then
          SUBJECT="✅ Terraform Apply Successful"
        else
          SUBJECT="❌ Terraform Apply Failed"
        fi
      - echo "Sending email with Subject: $SUBJECT"
      - |
        aws ses send-email \
          --from "jpandeer15@gmail.com" \
          --to "jagritpandeer1969@gmail.com" \
          --subject "$SUBJECT" \
          --text "$(cat tf_output.json || echo 'Check logs for failure')"
artifacts:
  files:
    - tf_output.json
    - status.txt
