version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
      - chmod +x send_email.sh

  pre_build:
    commands:
      - echo Initializing Terraform
      - terraform init

  build:
    commands:
      - echo Running Terraform Plan
      - |
        if ! terraform plan -out=tfplan; then
          ./send_email.sh "Terraform Plan Failed" "Terraform plan failed in CodeBuild."
          exit 1
        fi

  post_build:
    commands:
      - echo Applying Terraform
      - |
        if terraform apply -auto-approve tfplan; then
          terraform output > tf_output.txt
          ./send_email.sh "Terraform Apply Succeeded" "$(cat tf_output.txt)"
        else
          ./send_email.sh "Terraform Apply Failed" "Terraform apply failed in CodeBuild."
          exit 1
        fi
